### ISSUE TITLE
There is no /godata folder

### ISSUE THREAD

**Issue by bijookha** [gocd/docker-gocd-server#10]
Running docker server with

> $ docker run -d -p8153:8153 -p8154:8154 gocd/gocd-server

Then I create an agent, and configure some piplelines. Everything works as expected, except there is no godata folder to be found.

> $ docker ps

> CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS              PORTS                              NAMES
> 7877bc052f02        gocd/gocd-server                       "/sbin/my_init"          13 minutes ago      Up 13 minutes       0.0.0.0:8153-8154->8153-8154/tcp   xenodochial_tesla

> $ docker exec -i -t 7877bc052f02 bash -l
> root@7877bc052f02:/tmp# ls /godata
> ls: cannot access /godata: No such file or directory

What I want to do is mount the said /godata folder from a local folder on my machine (so that the config changes can be saved and reused) using the following command

$ docker run -d -p8153:8153 -p8154:8154 -v ~/demo/godata/:/godata gocd/gocd-server

But it does not save anything in ~/demo/godata on the host machine since the /godata folder is not created in the first place in the container.

So, essentially, where are the config, plugins, hostorical data etc being stored? It is not being stored in /godata as the documentation suggests.

Regards and Thanks

**Comment by bijookha** [comment]
Update:

There is however an autocreated folder called ehcache_auto_created_1490807394755 in /tmp.
Thought this might be useful information.
Still, the folder name is random and I can not mount using this. So, my problem remains.

> 
> root@3739aa4b44a1:/tmp# ls
> ehcache_auto_created_1490807394755  hsperfdata_go
> root@3739aa4b44a1:/tmp# ls ehcache_auto_created_1490807394755/
> com.thoughtworks.go.config.EnvironmentVariableConfig.data  com.thoughtworks.go.domain.User.data                      org.hibernate.cache.UpdateTimestampsCache.data
> com.thoughtworks.go.domain.NotificationFilter.data         com.thoughtworks.go.domain.User.notificationFilters.data
> com.thoughtworks.go.domain.Plugin.data                     org.hibernate.cache.StandardQueryCache.data
> root@3739aa4b44a1:/tmp#

**Comment by bijookha** [comment]
Host machine is archlinux.

**Comment by varshavaradarajan** [comment]
@bijookha , Can you please confirm if you are using the alpine based gocd server image provided [here](https://hub.docker.com/r/gocd/gocd-server/) ?

**Comment by bijookha** [comment]
Yes, I assume it is the same one because I used
$ docker pull gocd/gocd-server
which will pull from the link you provided. I can do some debugging if you guide me.

**Comment by varshavaradarajan** [comment]
`$ docker pull gocd/gocd-server` cannot work because we do not publish the latest tag. And as you can see from [dockerhub](https://hub.docker.com/r/gocd/gocd-server/tags/), we do not have the latest tag. Perhaps you had done the pull prior to March 20th? That's when we moved our existing phusion based images for previous gocd installations to [gocd-server-deprecated](https://hub.docker.com/r/gocd/gocd-server-deprecated) 

Can you run `cat /etc/os-release` and check if the name is `alpine linux` ?

**Comment by bijookha** [comment]
Well, you are right. It turns out it is not alpine. I indeed pulled before 20th March.
I will remove this image and pull again, and confirm if it fixes my problem. It will take some time (~1hr) since I have very slow internet.
But I do not understand how I got this Ubuntu 14.04 image, and would like to understand.
Also, it will be great if you can tell me what is the tag I should use since you do not publish 'latest'. Will 'v17.3.0' do? 

Thanks for your help. Really appreciate it.


> $ docker run -d -p8153:8153 -p8154:8154 gocd/gocd-server
> 2269b3b8cfddd07052ad7997f5a824532509f423f095c457c603e8ea846a3452
> 11:10 PM  ~ 
> $ docker exec -it 2269 bash -l
> root@2269b3b8cfdd:/tmp# cat /etc/os-release 
> NAME="Ubuntu"
> VERSION="14.04.3 LTS, Trusty Tahr"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 14.04.3 LTS"
> VERSION_ID="14.04"
> HOME_URL="http://www.ubuntu.com/"
> SUPPORT_URL="http://help.ubuntu.com/"
> BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
> root@2269b3b8cfdd:/tmp# 
>

**Comment by arvindsv** [comment]
@bijookha I just ran this:

```
$ docker run -p8153:8153 -p8154:8154 gocd/gocd-server:v17.3.0
Unable to find image 'gocd/gocd-server:v17.3.0' locally
v17.3.0: Pulling from gocd/gocd-server
627beaf3eaaf: Pull complete
ddcd4eb4b1fe: Pull complete
6a95748c77a8: Pull complete
f72b0dbc763e: Pull complete
Digest: sha256:b37f90c8bf243229cd5109316410d94fdc0ec51a39af8269af9ae739dbfb9d89
Status: Downloaded newer image for gocd/gocd-server:v17.3.0
/docker-entrypoint.sh: Creating directories and symlinks to hold GoCD configuration, data, and logs
$ mkdir /go-working-dir
$ chown go:go /go-working-dir
$ mkdir -v /godata/artifacts
$ chown go:go /godata/artifacts
created directory: '/godata/artifacts'
$ ln -sv /godata/artifacts /go-working-dir/artifacts
'/go-working-dir/artifacts' -> '/godata/artifacts'
$ chown go:go /go-working-dir/artifacts
$ mkdir -v /godata/config
created directory: '/godata/config'
$ chown go:go /godata/config
$ ln -sv /godata/config /go-working-dir/config
'/go-working-dir/config' -> '/godata/config'
$ chown go:go /go-working-dir/config
$ mkdir -v /godata/db
created directory: '/godata/db'
$ chown go:go /godata/db
$ ln -sv /godata/db /go-working-dir/db
$ chown go:go /go-working-dir/db
'/go-working-dir/db' -> '/godata/db'
$ mkdir -v /godata/logs
created directory: '/godata/logs'
$ chown go:go /godata/logs
$ ln -sv /godata/logs /go-working-dir/logs
'/go-working-dir/logs' -> '/godata/logs'
$ chown go:go /go-working-dir/logs
$ mkdir -v /godata/plugins
$ chown go:go /godata/plugins
created directory: '/godata/plugins'
$ ln -sv /godata/plugins /go-working-dir/plugins
$ chown go:go /go-working-dir/plugins
'/go-working-dir/plugins' -> '/godata/plugins'
$ mkdir -v /godata/addons
$ chown go:go /godata/addons
created directory: '/godata/addons'
$ ln -sv /godata/addons /go-working-dir/addons
'/go-working-dir/addons' -> '/godata/addons'
$ chown go:go /go-working-dir/addons
```

```
$ docker images
REPOSITORY                               TAG                 IMAGE ID            CREATED             SIZE
gocd/gocd-server                         v17.3.0             63e742db5118        5 days ago          493 MB
```

```
$ docker ps
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                              NAMES
7137771147d1        gocd/gocd-server:v17.3.0   "/docker-entrypoin..."   29 seconds ago      Up 26 seconds       0.0.0.0:8153-8154->8153-8154/tcp   jovial_cray
```

```
$ docker exec -i -t jovial_cray bash
bash-4.3# ls /godata/
addons     artifacts  config     db         logs       plugins
```

Finally, accessing `http://localhost:8153/go` works.

**Comment by varshavaradarajan** [comment]
That's because our old images had [phusion](https://github.com/phusion/baseimage-docker/blob/next/image/Dockerfile) as the base image which had ubuntu has its base image. 

Yes, you can use `v17.3.0`. So, `docker pull gocd/gocd-server:v17.3.0` will work. 

Closing this issue.
