### ISSUE TITLE
Cannot install plugins from inside a Dockerfile

### ISSUE THREAD

**Issue by gchinis** [gocd/docker-gocd-server#25]
I am trying to create a custom image that installs a couple of plugins. Following the instructions in the gocd-server page on how to install a plugin I created the following Dockerfile:

`
FROM gocd/gocd-server:v17.4.0

RUN [ "mkdir", "-p", "/godata/plugins/external"]

ADD ["https://github.com/tomzo/gocd-yaml-config-plugin/releases/download/0.4.0/yaml-config-plugin-0.4.0.jar", "/godata/plugins/external/yaml-config-plugin-0.4.0.jar"]

RUN [ "/bin/chown", "-R", "1000", "/godata/plugins/" ]
`

The problem is that the chown command has no effect thus leaving the plugin owned by root and inaccessible by the go-server.

I suspect that the source of the problem is that /godata is a volume as explained [here](http://stackoverflow.com/questions/26145351/why-doesnt-chown-work-in-dockerfile/26145444#26145444)

**Comment by varshavaradarajan** [comment]
@gchinis - checkout http://container-solutions.com/understanding-volumes-docker/.
The section on permissions and ownership mentions that -
>  A key point to be aware of here is that anything after the VOLUME instruction in a Dockerfile will not be able to make changes to that volume

**Comment by gchinis** [comment]
@varshavaradarajan - Thanks, that what I also understood but I believe that is very inconvenient. I suspect that the base image has declared the /godata as a VOLUME which means that derivative images cannot install any plugins at build time.  I believe it is common in the docker world for people to build custom images that match their use cases instead of configuring the software when they deploy it (trying to build immutable infrastructure etc). Is there another way to install the plugins in the gocd-server image at build time?

**Comment by arvindsv** [comment]
The only way I can think of to make this all work fine is to use an `-onbuild` image to base off of, without the volume.

**Comment by gchinis** [comment]
Looking at the code, I see that the docker-entrypoint.sh links the contents of /godata to /go-working-dir. Could a solution be that there is another directory something like /godata-extra that is not a volume and whose content is also linked to /go-working-dir?

**Comment by arvindsv** [comment]
I feel that would complicate it more, and it would be really hard to describe (in documentation, say) which one is  to be used.

**Comment by helmesjo** [comment]
I can second this.

Actually doing the exact same thing, expected to be able to install the yaml-config-plugin at build time so that the whole image is setup & ready to be run, and managed in a more automatic way (instead of relying on externally downloading & mounting it).

**Comment by EugenMayer** [comment]
i made a PR #50 to introduce plugin installation using ENV var so exactly those images are no longer needed - for just adding a set of plugins ( which we all will need ) - and making gocd/gocd-server a worthless image to directly start with. 

It does not really "fix" fix this, see #45 for more options for the special cases where -base is needed without volumes - in any case, i would rework this patch, its just the wrong way IMHO
