### ISSUE TITLE
Cannot use the bundled plugin yum-repo-exec-poller.jar

### ISSUE THREAD

**Issue by chrislovsund** [gocd/docker-gocd-server#26]
I get an error when trying to use YUM repo poller since `repoquery` binary is not found in Alpine.
I cannot find it in any package on [pkgs.alpinelinux.org](https://pkgs.alpinelinux.org/contents?file=repoquery&path=&name=&branch=&repo=&arch=)

> Interaction with plugin with id 'yum' implementing 'package-repository' extension failed while requesting for 'latest-revision-since'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Cannot run program "repoquery": error=2, No such file or directory']

**Comment by ketan** [comment]
Chris,

The plugin expects to find the `repoquery` program, which is usually available on centos/redhat and debian/ubuntu systems.

If you're looking to use the yum plugin, consider using a centos based base image instead. Changing the `FROM` line in the dockerfile should mostly suffice for this need.

**Comment by chrislovsund** [comment]
Ok, but then I have to build and install my own GoCD Centos docker image?
Since the Debian version, we used before is no longer supported?

**Comment by ketan** [comment]
Correct, that is what you'd have to do for now. If there's sufficient interest in a debian based image, we'd be more than happy to build one.
