### ISSUE TITLE
Could not create directory '/home/go/.ssh'

### ISSUE THREAD

**Issue by dreamlover** [gocd/docker-gocd-server#31]
I have created my docker instance from this image on CentOS 7 as bellow: 
```bash
#!/bin/bash
docker run \
    -d -p 81:8153 -p 82:8154 \
    -v /root/AYData/GoCD/Server:/godata:z \
    -v /root:/home/go:z \
    --name ay-gocd-server \
    gocd/gocd-server:v17.5.0
```
Followinge error showed when I was trying to test connection to a git repository.
```bash
Error performing command: --- Command ---
git ls-remote "ssh://lfree@i.ayjiayou.com:84/MPos-WebAPI.git " refs/heads/master
--- Environment ---
{GIT_ALLOW_PROTOCOL=http:https:ssh:git:file:rsync}
--- INPUT ----


--OUTPUT ---

--- ERROR ---
STDERR: Could not create directory '/home/go/.ssh'.
STDERR: Host key verification failed.
STDERR: fatal: Could not read from remote repository.
STDERR: 
STDERR: Please make sure you have the correct access rights
STDERR: and the repository exists.
---
```
The `.ssh` folder already exists in `/root` on the host system, why does the GoCD try to create another one?

**Comment by varshavaradarajan** [comment]
The .ssh directory must be owned by the go user in the container and the permissions must be `-rw------- (500)`. Have you checked that?

**Comment by ketan** [comment]
> The .ssh directory must be owned by the go user in the container and the permissions must be -rw------- (500). Have you checked that?

Add that to the troubleshooting section on this and the agent repos?

**Comment by dreamlover** [comment]
@varshavaradarajan Thank you for quick reply! :)
I checked that, if I mount the host OS's /root folder to the container at /home/go,  it will belonged to root:root, and has -rw------- permission.
Then I created another container without the /home/go mounting, letting the container create it by itself. After tried the same git repo connection, a .ssh folder was created inside the container in /home/go, but it was empty, namely no id_rsa/id_rsa.pub files generated. And the testing result is as bellow:
```bash
Error performing command: --- Command ---
git ls-remote "ssh://lfree@i.ayjiayou.com:84/MPos-WebAPI.git " refs/heads/master
--- Environment ---
{GIT_ALLOW_PROTOCOL=http:https:ssh:git:file:rsync}
--- INPUT ----


--OUTPUT ---

--- ERROR ---
STDERR: Host key verification failed.
STDERR: fatal: Could not read from remote repository.
STDERR: 
STDERR: Please make sure you have the correct access rights
STDERR: and the repository exists.
---
```

**Comment by varshavaradarajan** [comment]
@dreamlover , we provided the option for you to mount things like ssh keys to /home/go precisely for the same reason. SSH keys won't be generated for you. You must generate it yourself and mount it so that it will be available for the go user under `/home/go/.ssh`. The reason is that you wouldn't want new ssh keys generated each time you start a new container. That would mean adding the public keys to your remote server every time. So, what you can do is copy the keys to a directory you want to volume mount, chown the contents in this directory to `go (or UID 1000 if you are using our docker alpine image)`, chmod the private key to `500 (-rw-------)` and do
`docker run -v<your_directory>:/home/go ...`

**Comment by dreamlover** [comment]
@varshavaradarajan You mean chown the .ssh folder in the host OS?

**Comment by varshavaradarajan** [comment]
Yes. The ssh keys from the host machine is what you'll be volume mounting to the container.

**Comment by dreamlover** [comment]
But the **go** is a user inside the container, right?

**Comment by varshavaradarajan** [comment]
Yes, you can do chown to UID 1000 (the uid of the go user that we have setup in the image if you look at the dockerfile - https://github.com/gocd/docker-gocd-server/blob/master/Dockerfile#L39 ) on the host machine. 

Doing the chown for the ssh keys is similar to the instructions we have added here -https://github.com/gocd/docker-gocd-server#installing-plugins

**Comment by dreamlover** [comment]
@varshavaradarajan I have tried as you said:
```bash
mkdir ~/AYData/GoCD/GoHome
cp -a ~/.ssh ~/AYData/GoCD/GoHome
cd ~/AYData/GoCD/GoHome
chown -R 1000 .ssh/* # user 1000 is 'ay' inside host OS and 'go' inside the container
chmod 500 id_rsa # permission 500 is r_x, but you also side rw_, so I chmod it to 700(rwx)
docker run -v ~/AYData/GoCD/GoHome:/home/go:z ... # both gocd server and agent are the same
```
It did work! Thanks again! :)
