### ISSUE TITLE
Cannot pull from docker hub. 

### ISSUE THREAD

**Issue by charlesbthomas** [gocd/docker-gocd-server#39]
Currently unable to pull this image (or any other gocd image for that matter) from dockerhub. 

See error below:

```Error response from daemon: manifest for gocd/gocd-server:latest not found```

Seeing a similar error on other repos your org manages.

**Comment by arvindsv** [comment]
@charlesbthomas: We don't publish the `latest` tag. The available tags are published [here](https://hub.docker.com/r/gocd/gocd-server/tags/). There are some posts which people have written about (not) using the latest tag.

http://container-solutions.com/docker-latest-confusion/
http://blog.benhall.me.uk/2015/01/dockerfile-latest-tag-anti-pattern/

It is like force pushing, every time, and seems to cause more confusion than it is worth. Docker hub doesn't allow us to change the default command it shows, though. :(

**Comment by charlesbthomas** [comment]
@arvindsv The specified tags are not working either.

**Comment by varshavaradarajan** [comment]
@charlesbthomas , can you paste your docker pull command?

**Comment by arvindsv** [comment]
I just tried these:

```
$ docker pull gocd/gocd-server:v17.8.0
v17.8.0: Pulling from gocd/gocd-server
88286f41530e: Already exists
c3769f535438: Downloading [==============================================>    ]    213MB/230MB
c3769f535438: Pull complete
99f3d77488d6: Pull complete
Digest: sha256:7f474c944b879220def25c0f00daceb06be65a7c6585bc2fcbfdc428988819ed
Status: Downloaded newer image for gocd/gocd-server:v17.8.0
```

```
$ docker pull gocd/gocd-server:v17.9.0
v17.9.0: Pulling from gocd/gocd-server
88286f41530e: Already exists
2e511f49b568: Pull complete
aaa6c53a40ca: Pull complete
Digest: sha256:a466b96b83ae5832bb9c99dea7ffc3044de15ac37c023fc9dcf320c95ff718c4
Status: Downloaded newer image for gocd/gocd-server:v17.9.0
```

**Comment by charlesbthomas** [comment]
```docker pull lifeway/gocd-server:v17.9.0```

and here is the result:
```Error response from daemon: manifest for lifeway/gocd-server:v17.9.0 not found```

GoCD repositories are the only repo's my team and I are unable to pull from.

**Comment by Davel-11** [comment]
What I did was to find the docker tag
such as 
docker pull gocd/gocd-server:tagInfo

it worked for me
