### ISSUE TITLE
where to get available go-server and go-agent download link?

### ISSUE THREAD

**Issue by colachg** [gocd/docker-gocd-server#4]
```
ARG DOWNLOAD_URL="https://download.gocd.io/binaries/17.2.0-4587/generic/go-server-17.2.0-4587.zip"
```
* Is there a list to get available release download links like above? If I want to build locally use specific version.

**Comment by varshavaradarajan** [comment]
@colachg , you can find it from the download page on the website www.gocd.io/download. If you are looking for a list of all available releases, I suggest you to go through https://download.gocd.io/releases.json. Closing the issue.
