### ISSUE TITLE
No volume defintion?

### ISSUE THREAD

**Issue by EugenMayer** [gocd/docker-gocd-server#45]
The Dockerfile does not include any volume defintion, this would mean the whole server is stateless, which is not the case, right?

/godata/addons | the directory where GoCD addons are stored
/godata/artifacts | the directory where GoCD artifacts are stored
/godata/config | the directory where the GoCD configuration is store
/godata/db | the directory where the GoCD database and configuration change history is stored
/godata/logs | the directory where GoCD logs will be written out to
/godata/plugins | the directory containing GoCD plugins
/home/go | the home directory for the GoCD server

Its good practise to put the volume defintion into the Dockerfile ( or several, depending on the layout above there ).

So it least we should do 

```
VOLUME /godata
```

Did i miss something obvious so this gets invalid altogether?

**Comment by varshavaradarajan** [comment]
@EugenMayer - please refer to https://github.com/gocd/docker-gocd-server/issues/25  and https://github.com/gocd/docker-gocd-server/commit/8c3b9f90a81a296cc95f2f34e13c6eea39b172d0 as to why this was done. You could still do a volume mount to the /godata directory from a host even if its not explicitly declared as one in the dockerfile.

**Comment by varshavaradarajan** [comment]
Same for agents as well, in case you want to refer to that - https://github.com/gocd/docker-gocd-agent/commit/e1f47886945e88b4cee07103935311833fb16087

**Comment by EugenMayer** [comment]
Wait, thats just the wrong solution for a thing. please do NOT design gocd/gocd-server as a "base" image - design it as _the_ image to run. There is no plain reason to _always_ derive it, its special case doing that.

That said, you could go several ways. You create 2 images:
 - gocd-server-base ( just the current Dockerfile, but rather rename it to Dockerfile_base
 - gocd-server with

```
FROM gocd-server-base
VOLUME /godata
```
  
What you will otherwise create is a bad reputation of your own image, by people running it and lose all their data - and this reputation goes before the convenience to create custom images, which by the way can be avoided in a lot more cases. E.g by https://github.com/gocd/docker-gocd-server/issues/46

but much more by things like those kinds https://github.com/disaster37/webcenter-catalog/blob/master/templates/gocd/3/docker-compose.yml.tpl#L22

So rather more intelligent entrypoint logic e.g. pulling plugins by ENV vars, in this case, its implemented using confd + a template, see https://github.com/disaster37/alpine-gocd-server/blob/master/Dockerfile

The point is, this image should be production ready, not "build on top of it please". I understand that making the docker-entrypoint more powerful is work and is not the core focus now, but still, volumes are a must and this is the docker-ecosystem default by any docker-image worth of mentioning - we should not do it differently here.

**Comment by EugenMayer** [comment]
Possible we could also do https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#onbuild depending on the real issue here with the actual volume

**Comment by EugenMayer** [comment]
Probably not very clear here, i am perfectly aware that i simply can and always should use a named volume for that anway. We are talking about the case someone is not aware and just the general case.

You will find this in all docker images:

https://github.com/docker-library/percona/blob/52abf70205354001f24432c0c677be4a0264ef47/5.7/Dockerfile#L85

https://github.com/docker/distribution-library-image/blob/bc5d4f15a7e8d12ed6e5174ac4edab4b6032d09f/Dockerfile#L11


---

Only interprete / daemon only container do not expose a VOLUME since they have no idea what to persist and it needs to be done by the user always - but in your case, its a ready to use app and you know what you need. E.g. tomcat is the one without volume

https://github.com/docker-library/tomcat/blob/5a78361a9ce7ef48979acbcabe2acd9342d0168a/7/jre7/Dockerfile

Images that want / think about them being derived only ( not your case .. you are a _ready to use app!_ ) do it with a additional :onbuild tagged image https://github.com/docker-library/ruby/blob/a6918175fd506b46bf2d8f899f4faa40e72296fb/2.4/jessie/onbuild/Dockerfile

like https://hub.docker.com/_/ruby/ so the "-base" image is quiet common for them. So if you want to encourage inheritance, do that, instead of dismantling your actual application :D

**Comment by varshavaradarajan** [comment]
> There is no plain reason to always derive it, its special case doing that. ... by people running it and lose all their data

Yes, you're right about it being one of the ways that people use docker images. But I don't see why that would mean that we should provide 2 official docker images.  Can you please explain how this would make anybody lose any data? What I have understood is that  doing a docker run -it -v<host_dir>:/godata will ensure that the data is persisted once the docker container running the go server stops. Not declaring a volume mount in the dockerfile will not result in a loss of data. We've documented how to use this too. Please let us know if you find that there is anything lacking. :) 

I understand from https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#volume that it is good to have it declared, but conforming to this is not necessary in my opinion as having the volume instruction in the dockerfile serves little purpose here. May be I am mistaken. Would @ketan or @arvindsv like to comment? Its not that we're dismantling the image just to cater to a set of users who use ours as a base image, but this image can by used directly **and** as a base image as well. 

Also, the image is production ready. But some users do extend our image to install packages related to say, a proxy (nginx), packages needed to run our addons, etc, which aren't required to have a prod go server, but may be necessary in order to have the things I just mentioned. These are the kind of users who would want to use our image as the base. Doesn't mean that its unusable directly because of the missing volume instruction in the dockerfile.

**Comment by arvindsv** [comment]
What I remember is that everyone had issues with VOLUME instruction there and people have lesser issues without it. That's a small win, in my book. No one has complained about losing data and I'd assume that they know enough about Docker that they'd know that a volume is necessary to maintain data across containers.

We did consider using an onbuild image, as you can see in other comments, but I didn't see the need to complicate it and cause confusion between two images.

**Comment by EugenMayer** [comment]
without a VOLUME defintion, if i would start the container without `-v data:/godata` i would lose all data. With the VOLUME defintion, i would not lose, since `/godata` will ge an anon-volume automatically.

so `docker run -p 8153:1853 gocd/gocd-server:17 `  already means, you lose your data, when VOLUME has not been defined in the dockerfile. That is while all services which have persistent data _always_ ensure they define the VOLUME, so data is persisted, even if not on a named volume

**Comment by EugenMayer** [comment]
@arvindsv i cannot be, that someone "derives" from an image but does not care from "which", so he will always lookup the dockertags. I know you are familiar with ruby, see my link above, even they do onbuild builds for the exact same reasons

**Comment by arvindsv** [comment]
I've thought about this for a bit. I don't think adding the volume definition (and hence protecting people who choose to run this without `-v`) meaningful. It's documented how to use volume definitions and if you use Docker, you'll know what to do. As mentioned in a different thread, it's a technical use case, and whoever uses it will be technical. So, I'm closing this. I'm closing another related old issue, which argued to remove the existing VOLUME definition as well (https://github.com/gocd/gocd-docker/issues/21). Having that VOLUME definition caused multiple problems to people, around permissions and flexibility. I don't think we should go back on it. If someone really wants to, they can create another image with the VOLUME clause in it. That's the good thing about the docker ecosystem, at least. We don't all need to agree all the time.

I did think about creating a proper base image with on-build, but the fact that the name will have to change for people to continue using the image (gocd-server will essentially move to gocd-server-base) makes me not want to that.

**Comment by EugenMayer** [comment]
Well I guess this one will cross your road later once again later but as you might think, it was not a personal issue for me in any way, so I am fine with closing this one, I do not necessarily agree on the case though. Thanks for consideration
