### ISSUE TITLE
use the custom-entrypoint-scripts paradigm

### ISSUE THREAD

**Issue by EugenMayer** [gocd/docker-gocd-server#46]
You can see this in percona/mysql and a lot others, its always the same

https://github.com/EugenMayer/docker-image-atlassian-confluence/blob/master/bin/docker-entrypoint.sh#L82

https://github.com/EugenMayer/docker-image-atlassian-confluence/blob/master/bin/custom_scripts.sh

or inline like in https://github.com/docker-library/percona/blob/52abf70205354001f24432c0c677be4a0264ef47/5.7/docker-entrypoint.sh#L165

This way we could mount custom scripts like installing plugins and much more. this will avoid the gazzilion custom image images, but also enables a lot better and easier "start gocd stack from the ground" as a developer, as a gocd starter, by mounting those scripts, depending on what you do.

This paradigm proved to be very handy already, while very little overhead on no dependencies in the image. Kinda win only

**Comment by ketan** [comment]
+1. I've seen quite a few other TWers ask for this.

**Comment by EugenMayer** [comment]
ok, making a pull request later, setting up a docker-compose based gocd vanilly repo so we can use this in the docs but also in this repo. It will include the patch, give me a second for that. Great you like it

**Comment by varshavaradarajan** [comment]
Fixed in v17.12.0. Thanks @EugenMayer.
