### ISSUE TITLE
please provide :latest

### ISSUE THREAD

**Issue by EugenMayer** [gocd/docker-gocd-server#47]
I understand, for production use the versioned tag is great, but for the demo docker-compose files its rather a hinder. Its usual that the latest build does publish latest, or at least, that you have

:v17
:v16

for the latest build of the main release

**Comment by varshavaradarajan** [comment]
I would say that somebody using docker compose or just as a single container will not be sure of which version of go server they are running it with if "latest" or v17, which poses the same problem, is used. Latest doesn't always guarantee that one has the newest release of the image on their host anyway. I think that it pinning a specific version to use in the yaml file is fine.

**Comment by EugenMayer** [comment]
I do not really agree, but i do not see .a huge benefit either, so feel free to close if you like
