### ISSUE TITLE
GOCD_FULL_VERSION is not documented and needs to be set when building

### ISSUE THREAD

**Issue by EugenMayer** [gocd/docker-gocd-server#53]
needs to be fixed in the readme

**Comment by varshavaradarajan** [comment]
Thanks @EugenMayer - addressed by https://github.com/gocd/docker-gocd-server/commit/f06444f178faa806808b40e9928cc9af4ecba1d4

**Comment by EugenMayer** [comment]
Well no you gave the user a variable and did not explain what it is. Since there is a version, and now there is a full version - telling the difference is very important
