### ISSUE TITLE
docker pull failure with tag latest

### ISSUE THREAD

**Issue by BarathArivazhagan** [gocd/docker-gocd-server#56]
While trying to pull docker image from dockerhub, I am getting below error: 

```
docker pull gocd/gocd-server
Using default tag: latest
Error response from daemon: manifest for gocd/gocd-server:latest not found
```
Is it possible to attach a latest tag to one of the stable image ? 

or we have to use only tag specific docker images ?

**Comment by varshavaradarajan** [comment]
@BarathArivazhagan - we don't provide the latest tag for our docker image. Currently, the latest stable tag is `v17.11.0`. So, you can do `docker pull gocd/gocd-server:v17.11.0` . You might want to check https://github.com/gocd/docker-gocd-agent/issues/10#issuecomment-294933192 out for why we don't provide the latest tag.
