### ISSUE TITLE
Add support for hooks in docker-entrypoint.sh

### ISSUE THREAD

**Issue by akshaykarle** [gocd/docker-gocd-server#59]
Hello go team,

We would like to have some hooks in the `docker-entrypoint.sh` before starting go-server for setting up credentials and SSH keys that we'd like to fetch only at run time of the docker container.

Anyway you could add support for allowing to run scripts? Maybe a directory where we can add the bash scripts that setup up the credentials?

Cheers,
Akshay

**Comment by ketan** [comment]
Closing as dup of #46. See https://github.com/gocd/docker-gocd-server#running-custom-entrypoint-scripts
