### ISSUE TITLE
Configurable timezones during docker run

### ISSUE THREAD

**Issue by kishaningithub** [gocd/docker-gocd-server#63]
The default timezone within this image is in UTC due to which the cron triggers for pipelines will trigger the pipeline based on that. This needs to be configurable based on may be an environment variable where i can specify the timezone

Ref
https://wiki.alpinelinux.org/wiki/Setting_the_timezone

**Comment by ketan** [comment]
See https://github.com/gocd/docker-gocd-server/blob/master/README.md#running-custom-entrypoint-scripts to customize the container to your needs.
