### ISSUE TITLE
Console log is not persisted between restart for running pipeline

### ISSUE THREAD

**Issue by bdpiprava** [gocd/docker-gocd-server#68]
### Steps
1. Run gocd server using Docker
2. Trigger a pipeline
3. Restart GoCD server container when a pipeline is running
    - As GoCD server stores console log in `data/console` when the pipeline is running and it is not symlinked to `godata` directory

After the restart in a new container, GoCD starts logging console log in a new file and loses console log written by the previous container.

**Comment by arvindsv** [comment]
@bdpiparva I've seen something similar happening with a non-docker server too. Can we investigate that too, please, @adityasood?

**Comment by adityasood** [comment]
@arvindsv @bdpiparva I tried with the following

1. I created two pipelines, each with a  job which was continuously writing to the logs every 5 seconds.
2. They were running parallelly
3. I restarted the server with the following time difference ( kept it down for 1 minute, 5 minutes, 10 minutes)
4. We did lose the logs while the server was down (this is expected)
5. But the logs were written to the same respective files in (data/console) as and when the server was brought up
6. I tried cancelling the jobs and didnt have any residual log files in (data/console) folder.
7. While the jobs were running, I attempted several backups with none impacting the console logs

My server is not that bulky and maybe we can look at a bulkier instance for backup and see if that causes any issues.

Let me know what do you guys think. Also if you have such job on build.gocd.org let me know and I can spend sometime analyzing what could have caused this.

**Comment by ketan** [comment]
@adityasood — did you `docker stop` and `docker start`? Try `docker stop && docker rm && docker run` ?

**Comment by adityasood** [comment]
@ketan I was trying this on a non-docker setup, to verify that

**Comment by ketan** [comment]
Ok — sorry. Ignore my comment
