### ISSUE TITLE
GoCD docker image based on CentOS

### ISSUE THREAD

**Issue by ChrisRo89** [gocd/docker-gocd-server#73]
I created some weeks ago a docker image based on CentOS maybe that's interesting for here as well, you'll find it there:
https://github.com/ChrisRo89/docker-gocd-server

**Comment by varshavaradarajan** [comment]
@ChrisRo89 - thank you. Closing this as its not an issue. :) You can make a post on gocd google groups for users to check your image out - https://groups.google.com/forum/#!forum/go-cd or announce on gitter - https://gitter.im/gocd/gocd
