### ISSUE TITLE
Mismatch between documentation and script for installing plugins. 

### ISSUE THREAD

**Issue by childsc** [gocd/docker-gocd-server#79]
Hello,

There appears to be a mismatch between the documentation and the script for installing the plugins

Documentation:

Installing plugins using an environment configuration
> To install plugins, just add an ENV variable with the prefix GOCD_PLUGIN_INSTALL_ and your name as suffix and the value being the download URL. The plugin will only be downloaded if not yet present.

install-gocd-plugins - last change made:
`    if [ -e "${plugin_dest}" ]; then
      yell "Overwriting the plugin '$plugin_dest' with new jar."
      try rm "${plugin_dest}"
fi`

We can see in the history for the script the change was made in February 2018. 

Please clarify which is intended to be correct?

This is how I would like to see the plugins be treated:
1) on server start up there should be a check against the current plugins installed against the ones defined as ENV variables. 
    1.1) if a plugin does not exist in the "/godata/plugins/external" then it is downloaded
   .1.2) if there are old plugins which are not listed in the ENV variables then the plugin is removed.

**Comment by arvindsv** [comment]
@childsc Thank you for bringing this up.

@rajiesh I see you made a change in #80. Can this issue be closed then? Maybe @childsc should be the judge of it. :)

**Comment by arvindsv** [comment]
Looks like it's sorted out in #80. Closing. Unless anyone wants it reopened.
