### ISSUE TITLE
README usage instruction is pointing to incorrect server image name

### ISSUE THREAD

**Issue by ankitsri11** [gocd/docker-gocd-server#81]
Currently, all the usage instructions are pointing to the incorrect image name `gocd/docker-gocd-server:v19.4.0`. 

<img width="676" alt="Screenshot 2019-05-28 at 12 05 12" src="https://user-images.githubusercontent.com/6838313/58505085-f9c77800-8140-11e9-9f3a-004d2e4f2f65.png">

It should be pointing to `gocd/gocd-server:v19.4.0`

**Comment by arvindsv** [comment]
I've manually fixed the one on https://hub.docker.com/r/gocd/gocd-server/ for now. Haven't checked any others.
