### ISSUE TITLE
Large container image size since 19.6.0

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/docker-gocd-server#87]
Shouldn't it be possible to forego using the tanuki wrapper and start go.cd directly with java like

```
java ${JAVA_OPTS} -jar /go-server/lib/go.jar
```

I think it could massively reduce the size of the image. Looking at https://hub.docker.com/r/gocd/gocd-server/tags the size seems to have almost doubled when in 19.6.0 go.cd implemented https://github.com/gocd/gocd/issues/6627

**Comment by ketan** [comment]
Tanuki does not really add much (as compared to the JVM + glibc).

Unfortunately installing a java 11 on alpine requires us to install glibc because there is still no musl libc based java 11 available on alpine.

See:
- https://github.com/docker-library/openjdk/issues/211#issuecomment-426708580
- https://github.com/docker-library/openjdk/issues/212#issuecomment-424453577
- https://github.com/docker-library/openjdk/pull/235#issuecomment-424599754

**Comment by JorritSalverda** [comment]
By switching to adoptopenjdk:11-jre-hotspot (debian based) I manage to build a version at 298MB

See
- https://github.com/Travix-International/docker-gocd-server/blob/19.7.0/Dockerfile
- https://cloud.docker.com/u/travix/repository/docker/travix/gocd-server/tags

Still trying to stick with Alpine will the adoptopenjdk is much smaller makes no sense.

**Comment by JorritSalverda** [comment]
It also bypasses the wrapper by running `java ${JAVA_OPTS} -jar /var/lib/go-server/lib/go.jar ${GO_SERVER_ARGS}` straightaway.

See https://github.com/Travix-International/docker-gocd-server/blob/19.7.0/docker-entrypoint.sh#L46

**Comment by JorritSalverda** [comment]
Or you could use `adoptopenjdk/openjdk11:jre-11.0.4_11` which starts at 50MB (versus 80M for `adoptopenjdk:11-jre-hotspot`.

**Comment by ketan** [comment]
> Or you could use `adoptopenjdk/openjdk11:jre-11.0.4_11` which starts at 50MB (versus 80M for `adoptopenjdk:11-jre-hotspot`.

That is interesting, I'll take a look at why our image is comparatively larger (we've based our Dockerfile from adoptopenjdk's image)

**Comment by JorritSalverda** [comment]
I copied it from https://github.com/AdoptOpenJDK/openjdk-docker/blob/master/11/jre/alpine/Dockerfile.hotspot.releases.full. I do have less packages installed in my version, but I imagine to you can get your image size down quite a bit as well.

**Comment by ketan** [comment]
On a [closer look](https://microbadger.com/images/gocd/gocd-server:v19.7.0), it seems that the image adds 173mb at the last stage (chown/chmod).

Will take a look at this further next week. I think all the agent images would be similarly affected.

**Comment by GaneshSPatil** [comment]
Hi @JorritSalverda,

The current issue has been fixed as part of [this](https://github.com/gocd/gocd/pull/6826) commit.
After the fix, the download size of the GoCD Server has reduced from **`441.4 MB`** to **`261.4 MB`**.

Please take a look at the following MicroBadger inspection of GoCD container images:
- [GoCD Server v19.7.0 Docker Image](https://microbadger.com/images/gocd/gocd-server:v19.7.0)
- [Experimental GoCD Server v19.8.0 Docker Image](https://microbadger.com/images/gocdexperimental/gocd-server:v19.8.0-9829) (consisting of above-mentioned fix)

The description of the fix is mentioned [here](https://github.com/gocd/gocd/pull/6826#issuecomment-525123616).

Please do let us know if any further information is required.

Thanks!

**Comment by JorritSalverda** [comment]
That's a pretty big win, awesome. 

Our version is still some 20MB smaller, but that's because I don't install `cyrus-sasl`, `cyrus-sasl-plain`, `nss`, `mercurial`, `subversion`, `procps` and `tini` and remove the `wrapper`, `wrapper-config` and `bin` directories. But the users of the official image probably depend on half of those packages so probably can't be removed for that reason.

Hope you find similar savings in the agent images by discarding the `chown` command or running it as part of the same `RUN` command.

**Comment by ketan** [comment]
Can you clarify which chown you are referring to?

**Comment by JorritSalverda** [comment]
For example https://github.com/gocd/docker-gocd-agent-debian-9/blob/v19.7.0/Dockerfile#L75-L76.

It adds 30.6MB to the image size:

```
$ docker history gocd/gocd-agent-debian-9:v19.7.0

IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
105e6ddac683        4 weeks ago         /bin/sh -c #(nop)  USER go                      0B
<missing>           4 weeks ago         /bin/sh -c #(nop)  ENTRYPOINT ["/docker-entr…   0B
<missing>           4 weeks ago         |2 GID=1000 UID=1000 /bin/sh -c chown -R go:…   30.6MB
<missing>           4 weeks ago         /bin/sh -c #(nop) COPY --chown=go:rootmulti:…   2.99kB
<missing>           4 weeks ago         /bin/sh -c #(nop) COPY dir:92ac5b97750170a90…   30.6MB
<missing>           4 weeks ago         /bin/sh -c #(nop) ADD file:1872a96323c41db4b…   5.97kB
<missing>           4 weeks ago         |2 GID=1000 UID=1000 /bin/sh -c chmod 0755 /…   335MB
<missing>           4 weeks ago         /bin/sh -c #(nop)  ARG GID=1000                 0B
<missing>           4 weeks ago         /bin/sh -c #(nop)  ARG UID=1000                 0B
<missing>           4 weeks ago         /bin/sh -c #(nop)  ENV GO_JAVA_HOME=/gocd-jre   0B
<missing>           4 weeks ago         /bin/sh -c #(nop)  ENV LC_ALL=en_US.UTF-8       0B
<missing>           4 weeks ago         /bin/sh -c #(nop)  ENV LANGUAGE=en_US:en        0B
<missing>           4 weeks ago         /bin/sh -c #(nop)  ENV LANG=en_US.UTF-8         0B
<missing>           4 weeks ago         /bin/sh -c #(nop) ADD 69fa04524785343173838a…   870kB
<missing>           4 weeks ago         /bin/sh -c #(nop)  LABEL gocd.version=19.7.0…   0B
<missing>           4 weeks ago         /bin/sh -c #(nop)  MAINTAINER ThoughtWorks, …   0B
<missing>           7 weeks ago         /bin/sh -c #(nop)  CMD ["bash"]                 0B
<missing>           7 weeks ago         /bin/sh -c #(nop) ADD file:f615b611820773fd6…   101MB
```

**Comment by ketan** [comment]
This issue has been address for all agents as well.

See https://microbadger.com/images/gocdexperimental/gocd-agent-debian-9 and this comment: https://github.com/gocd/gocd/pull/6826#issuecomment-525123616

**Comment by JorritSalverda** [comment]
Ah clear. I didn't look at the PR close enough :)

**Comment by chadlwilson** [comment]
If I understand the conversation correctly, I think this was resolved so closing this now. Please let me know if I have misunderstood.
