### ISSUE TITLE
Is there a Docker image with both the GoCD Server and GoCD Agent installed?

### ISSUE THREAD

**Issue by shaunluttin** [gocd/docker-gocd-server#88]
We are putting GoCD into a DigitalOcean droplet. Since we have a small budget with a simple workflow, we would like to host the GoCD Server and Agent in the same droplet. We know we could do this by manually installing both the server and agent using `bash` over `ssh`. That said, we like using exisitng Docker images when they are available. Is there an existing GoCD docker image that includes an installation of both the GoCD server and agent?

**Comment by varshavaradarajan** [comment]
@shaunluttin - Why not have two different docker containers for server and agent on the same droplet?

**Comment by shaunluttin** [comment]
@varshavaradarajan Good idea. I did not know that was possible. I assume that means installing Docker on the droplet and then doing a `docker pull` and `docker run` for both the server and agent.

**Comment by varshavaradarajan** [comment]
@shaunluttin - yes, https://github.com/gocd/docker-gocd-agent-alpine-3.9#usage-with-docker-gocd-server should be helpful
